class UserModel {
  int? id = 0;
  String? userName = "";
  String? firstName = "";
  String? lastName = "";
  String? email = "";
  String? phoneNumber = "";
  String? lastLoginDate;
  String? status = "";
  String? agentIdentifier = "";
  String? address = "";
  String? city = "";
  String? lga = "";
  String? state = "";
  String? country;
  String? idType;
  String? idNumber;
  String? bvn = "";
  bool? pinReset = false;
  bool? needSetup = false;
  bool? changePassword = false;
  int? parentAgentId = 0;
  String? parentAgentName;
  String? agentType = "";
  String? classification = "";
  String? bankAccountNumber = "";
  String? bankInstitutionCode = "";
  String nin = "";
  String? rcNumber = "";
  String selfieBase64Img = "";
  late String idCardBase64Img;
  bool kycComplete = true;
  String? referralCode = "";
  String cacbase64Img = "";
  String fullName = '';
  String abbrName = '';
  String? businessName;

  void fromJson(Map<String, dynamic> data) {
    id = data['id'];
    agentType = data['agentType'];
    classification = data['classification'];
    bankAccountNumber = data['bankAccountNumber'];
    bankInstitutionCode = data['bankInstitutionCode'];
    nin = data['nin'] ?? '';
    rcNumber = data['rcNumber'];
    selfieBase64Img = data['selfieBase64Img'] ?? '';
    idCardBase64Img = data['idCardBase64Img'] ?? '';
    kycComplete = data['kycComplete'] ?? true;
    referralCode = data['referralCode'];
    cacbase64Img = data['cacbase64Img'] ?? '';
    parentAgentName = data['parentAgentName'];
    parentAgentId = data['parentAgentId'];
    pinReset = data['pinReset'];
    needSetup = data['needSetup'];
    changePassword = data['changePassword'];
    userName = data['userName'];
    firstName = data['firstName'] ?? '';
    lastName = data['lastName'] ?? '';
    email = data['email'];
    phoneNumber = data['phoneNumber'];
    lastLoginDate = data['lastLoginDate'];
    status = data['status'];
    agentIdentifier = data['agentIdentifier'];
    address = data['address'];
    city = data['city'];
    lga = data['lga'];
    state = data['state'];
    country = data['country'];
    idType = data['idType'];
    idNumber = data['idNumber'];
    bvn = data['bvn'];
    fullName = firstName! + ' ' + lastName!;
    abbrName = firstName!.substring(0, 1) + lastName!.substring(0, 1);
    businessName = data['businessName'];
  }
}
